### PR TITLE
Change map_cat field to value which is what the Vue app is looking for

### PR DESCRIPTION
**Pull request by mhines-usgs**

### CODE REVIEW

**Comment by mhines-usgs** [comment]
Not sure if you think I should also drop some of the data we don't need right now? 
image 

we really only need hru_id_nat and value

**Comment by wdwatkins** [comment]
I'd say let's leave the other columns, unless the csv is getting unwieldy due to the size.  Might be nice to be able to spot check the results.

**Comment by mhines-usgs** [comment]
Ok - that sounds like a good idea! thanks

**Comment by mhines-usgs** [comment]
On size, it's 10mb

**Pull request merged**
