### PR TITLE
adjust job to use slave; adjust param passing section

### PR DESCRIPTION
**Pull request by mhines-usgs**

### CODE REVIEW

**Comment by mhines-usgs** [comment]
Can't tell yet, but hopefully will be able to shortly :)

**Comment by mhines-usgs** [comment]
yay, working now. i'll adjust other downstream jobs to re-use the tier choice again 😂

**Comment by wdwatkins** [comment]
We also want this job to trigger the tile-join job — I guess that could be set up here, or at the tile join job?

**Comment by mhines-usgs** [comment]
I did it via Jenkins instead of in the pipeline, by setting a build trigger on the first job

**Pull request merged**
