### PR TITLE
Use proper content type for firefox

### PR DESCRIPTION
**Pull request by mhines-usgs**
to display the vector tiles

### CODE REVIEW

**Comment by tworr** [comment]
Looks good.  It might be good to wait on the merge until cloudfront catches up to my changes so I can do some final verification.

**Comment by mhines-usgs** [comment]
@tworr sounds good, no rush on my end. these are currently only outputting to wbeep-test-website in the tiles directory, which I am fairly certain @abriggs-usgs has hardcoded currently to point at beta bucket

**Comment by abriggs-usgs** [comment]
Yup. That is true. Both the 'test' and 'beta' buckets use the tiles in the 'beta' bucket. If you need it changed, I can do it manually.

**Comment by tworr** [comment]
Okay this should be good to go.  The HRU tiles are still showing in Chrome and now they work in Firefox from S3 with Content-Type application/x-protobuf.

**Pull request merged**
