### PR TITLE
only retry jenkins stage when the tier is prod

### PR DESCRIPTION
**Pull request by mhines-usgs**
based on https://dingyuliang.me/jenkins-declarative-pipeline-use-conditional-stages/
wondering if this will work, rather than having it retry the whole pipeline, try to focus it on the stage that might fail? If this works, there may be other docker pulls we want to precede with this?

### CODE REVIEW

**Comment by wdwatkins** [comment]
Worth trying, but wouldn't the retry need to be conditioned on the status of the build somehow?  This seems like it the build will just retry no matter what on Prod.  Looks like you can associate the `post` section with just a particular stage, rather than the whole job: https://jenkins.io/doc/book/pipeline/syntax/#post-conditions

You can also use tryCatch statement inside script blocks, but I'm not sure if you can wrap the `agent` block in a `script`.  https://stackoverflow.com/questions/44003788/try-catch-block-in-jenkins-pipeline-script

**Comment by mhines-usgs** [comment]
I think adding a post section in the stage that might fail is the best option, :thumbsup:

**Comment by mhines-usgs** [comment]
@isuftin curious if you have seen any declarative pipeline information out there (googling isn't helping me very much) where i can retry a stage if it fails, but only for a specific tier (prod) in our case. I've read you can't use when, you can't use if outside a script block, but haven't seen a combination of all the things i need anywhere so i don't feel so great about it.

**Comment by isuftin** [comment]
@mhines-usgs Is the solution in this PR not working?

**Comment by isuftin** [comment]
@mhines-usgs I think tryinng the post option as @wdwatkins suggests based on the stage is your best bet, and inside of an if block to test for type of buld

**Comment by mhines-usgs** [comment]
> @mhines-usgs Is the solution in this PR not working?

I haven't tried it yet because I just don't feel very confident about it. also i don't think the section will fail very often, so i need a way to actually test it without it failing by timing out as it did randomly on sunday night.

**Comment by wdwatkins** [comment]
For testing, I think you could just purposefully put an invalid address for the container registry.  Obviously it won't work on the retry either, but you should be able to see that it tries

**Comment by mhines-usgs** [comment]
k, i can try an invalid address. i'm still not totally sure if you guys think what my last pull request shows the behavior that david is suggesting, i think it does but again, i can't seem to find any good examples of this.

**Comment by wdwatkins** [comment]
I think the logic checks out, so as long as there isn't some issue with groovy it should be 👍

**Comment by mhines-usgs** [comment]
k, context here (until it scrolls away): https://jenkins.wma.chs.usgs.gov/job/MakerSpace/job/tippecanoe_tile_join/465/console 
```
Login Succeeded
[Pipeline] {
[Pipeline] isUnix
[Pipeline] sh
+ docker pull code.chs.usgs.gov:5001/wma/iidd/wbeep-data-processing:tippecanoe-latest
Error response from daemon: Get https://code.chs.usgs.gov:5001/v2/wma/iidd/wbeep-data-processing/manifests/tippecanoe-latest: Get https://code.chs.usgs.gov/jwt/auth?account=isuftin&scope=repository%3Awma%2Fiidd%2Fwbeep-data-processing%3Apull&service=container_registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[Pipeline] }
[Pipeline] // withDockerRegistry
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (push to S3)
Stage "push to S3" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```

**Pull request merged**
